name: build-pyorbit
on: push
jobs:
 centos-stream:
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream9
    steps:
         - name: Install packages
           run: |
             dnf group install -y "Development Tools"
             dnf install -y python3-devel openmpi-devel fftw3-devel

         - uses: actions/checkout@v4
           with:
            fetch-depth: 0

         - name: Build
           run: |
             .github/workflows/build.sh

         - name: Test
           run: |
             .github/workflows/run-tests.sh

 ubuntu:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
         - name: Install packages
           run: |
             apt-get update -y
             apt-get install -y  build-essential python3 openmpi-bin openmpi-common libopenmpi-dev
             apt-get install -y  zlib1g-dev libfftw3-dev python3-distutils python3-venv libpython3-dev git

         - uses: actions/checkout@v4
           with:
            fetch-depth: 0

         - name: Build
           run: |
             .github/workflows/build.sh

         - name: Test
           run: |
             .github/workflows/run-tests.sh
             

 conda:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
         - name: Install Conda
           run: |
             apt update -y
             apt install -y curl gpg git build-essential
             curl https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc | gpg --dearmor > conda.gpg
             install -o root -g root -m 644 conda.gpg /usr/share/keyrings/conda-archive-keyring.gpg
             echo "deb [arch=amd64 signed-by=/usr/share/keyrings/conda-archive-keyring.gpg] https://repo.anaconda.com/pkgs/misc/debrepo/conda stable main" > /etc/apt/sources.list.d/conda.list
             apt update -y
             apt install -y conda
             

         - uses: actions/checkout@v4
           with:
            fetch-depth: 0

         - name: Build
           run: |
             .github/workflows/build-conda.sh

         - name: Test
           run: |
             .github/workflows/conda-tests.sh